### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by uziassantosferreira** [nomanr/WeekCalendar#3]
Crash in android 4.4.2
 FATAL EXCEPTION: main
                                                                      Process: br.com.iclinic.debug, PID: 19043
                                                                      java.lang.ClassCastException: android.widget.RelativeLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
                                                                          at android.widget.GridView.onMeasure(GridView.java:1046)
                                                                          at android.view.View.measure(View.java:16772)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                          at android.view.View.measure(View.java:16772)
                                                                          at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
                                                                          at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
                                                                          at android.view.View.measure(View.java:16772)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at android.view.View.measure(View.java:16772)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
                                                                          at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:610)
                                                                          at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:677)
                                                                          at android.view.View.measure(View.java:16772)
                                                                          at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:940)
                                                                          at android.view.View.measure(View.java:16772)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                          at android.view.View.measure(View.java:16772)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                          at android.view.View.measure(View.java:16772)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at android.view.View.measure(View.java:16772)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                          at android.view.View.measure(View.java:16772)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2294)
                                                                          at android.view.View.measure(View.java:16772)
                                                                          at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1936)
                                                                          at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1133)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1315)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1020)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5762)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:757)
                                                                          at android.os.Handler.handleCallback(Handler.java:733)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:149)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by nomanr** [comment]
Code would help! where and how are you using the library? Share the code please.

**Comment by uziassantosferreira** [comment]
i really sorry, i resolve bug this is my bug in adapter.
Thanks help very fast.

**Comment by nomanr** [comment]
No problem
