### ISSUE TITLE
Unable to inflate it

### ISSUE THREAD

**Issue by tjouin** [nomanr/WeekCalendar#37]
Someone already seen this ?

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.app.android.yogowo, PID: 17193
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.android.yogowo/com.app.android.yogowo.Controllers.Main.Root}: android.view.InflateException: Binary XML file line #0: Error inflating class noman.weekcalendar.WeekCalendar
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                      at android.app.ActivityThread.access$800(ActivityThread.java:151)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                   Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class noman.weekcalendar.WeekCalendar
                      at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                      at com.app.android.yogowo.Controllers.Main.Feature.Calendar.View.onCreateView(View.java:57)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                      at android.support.v4.app.FragmentManagerImpl.ensureInflatedFragmentView(FragmentManager.java:1655)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1390)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1650)
                      at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1906)
                      at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3698)
                      at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:111)
                      at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:350)
                      at android.support.v4.app.BaseFragmentActivityApi14.onCreateView(BaseFragmentActivityApi14.java:39)
                      at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:67)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                      at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378)
                      at android.app.Activity.setContentView(Activity.java:2145)
                      at com.app.android.yogowo.Controllers.Main.Root.onCreate(Root.java:393)
                      at android.app.Activity.performCreate(Activity.java:5990)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5254) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.newInstance(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                      at com.app.android.yogowo.Controllers.Main.Feature.Calendar.View.onCreateView(View.java:57) 
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261) 
                      at android.support.v4.app.FragmentManagerImpl.ensureInflatedFragmentView(FragmentManager.java:1655) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1390) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1650) 
                      at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1906) 
                      at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3698) 
                      at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:111) 
                      at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:350) 
                      at android.support.v4.app.BaseFragmentActivityApi14.onCreateView(BaseFragmentActivityApi14.java:39) 
                      at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:67) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                      at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378) 
                      at android.app.Activity.setContentView(Activity.java:2145) 
                      at com.app.android.yogowo.Controllers.Main.Root.onCreate(Root.java:393) 
                      at android.app.Activity.performCreate(Activity.java:5990) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5254) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                   Caused by: java.lang.ClassCastException: com.app.android.yogowo.Controllers.Main.Root cannot be cast to android.support.v7.app.AppCompatActivity
                      at noman.weekcalendar.view.WeekPager.initPager(WeekPager.java:54)
                      at noman.weekcalendar.view.WeekPager.initialize(WeekPager.java:47)
                      at noman.weekcalendar.view.WeekPager.<init>(WeekPager.java:38)
                  	at noman.weekcalendar.WeekCalendar.init(WeekCalendar.java:6`

**Comment by G2EvolutionNarayana** [comment]
I have updated my android studio .so Now calander is not working

**Comment by abbasalill** [comment]
@tjouin have you got any solution?
